### ISSUE TITLE
Color-blind friendly palette for the diff-in-diffs figure

### ISSUE THREAD

**Issue by mizuhirosuzuki** [worldbank/r-econ-visual-library#25]
One of my friends told me that the color-blind friendly palette is not used for this [diff-in-diffs](https://worldbank.github.io/r-econ-visual-library/DiffinDiff_HISP.html) figure. 
I simply forgot to use a color palette in this figure, and I guess you can add 
```
  scale_color_brewer(palette = "Set2") +

```

in the ggplot expresion, as in https://worldbank.github.io/r-econ-visual-library/RDDCI.html.

**Comment by luizaandrade** [comment]
Thank you for pointing this out, @mizuhirosuzuki!
